version: "3.9"

services:
  rundeck:
    image: my-ansible-rundeck:latest
    ports:
      - "80:4440"
    volumes:
      - ./config:/home/myuser/rundeck/server/config
      - /srv/rundeck:/home/myuser/rundeck/server/data/
      - /srv/ansible:/home/myuser/rundeck/ansible/
